### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by zabelra** [RhoInc/CASI_MID#1]
![suppfig1a](https://cloud.githubusercontent.com/assets/14199771/11071856/00bdce4e-87b1-11e5-95de-ba76e2ca8859.png)
![suppfig1b](https://cloud.githubusercontent.com/assets/14199771/11071921/5004cdea-87b1-11e5-9996-a7b5d69e3704.png)
![suppfig1c](https://cloud.githubusercontent.com/assets/14199771/11071926/536d7dc4-87b1-11e5-9c4c-0b3e5d8c77f6.png)

**Comment by jwildfire** [comment]
Moved files to /img folder.
